import type { createDatabase } from '@capella/database';
import { branches, deviceAuthenticationChallenges, deviceHistory, devicePairingRequests, devices, employees } from '@capella/database/schema';
import { and, asc, count, eq, gt, isNull } from 'drizzle-orm';
import type { DeviceRepository, PublicDevice } from './devices-service.js';

type Database = ReturnType<typeof createDatabase>;
const publicDevice = (row: typeof devices.$inferSelect): PublicDevice => ({ id: row.id, assignmentType: row.assignmentType, assignmentId: row.assignmentType === 'employee' ? row.employeeId! : row.branchId!, status: row.status, browser: row.browser, platform: row.platform, pairedAt: row.pairedAt, lastUsedAt: row.lastUsedAt, revokedAt: row.revokedAt });
const duplicate = (error: unknown) => typeof error === 'object' && error !== null && (Reflect.get(error, 'code') === 'ER_DUP_ENTRY' || Reflect.get(Reflect.get(error, 'cause') ?? {}, 'code') === 'ER_DUP_ENTRY');
const assignmentFilter = (type: 'employee' | 'branch', id: number) => type === 'employee' ? eq(devices.employeeId, id) : eq(devices.branchId, id);

export const createDrizzleDeviceRepository = (database: Database, now: () => Date = () => new Date()): DeviceRepository => ({
  async assignmentExists(input) { if (input.assignmentType === 'branch') return Boolean((await database.select({ id: branches.id }).from(branches).where(eq(branches.id, input.assignmentId)).limit(1))[0]); return Boolean((await database.select({ id: employees.id }).from(employees).where(and(eq(employees.id, input.assignmentId), isNull(employees.deletedAt))).limit(1))[0]); },
  async createPairing(input) { return database.transaction(async (tx) => { if (input.assignmentType === 'employee') { const employee = await tx.select({ id: employees.id }).from(employees).where(and(eq(employees.id, input.assignmentId), isNull(employees.deletedAt))).for('update').limit(1); if (!employee[0]) return 'assignment_not_found' as const; } else { const branch = await tx.select({ id: branches.id }).from(branches).where(eq(branches.id, input.assignmentId)).for('update').limit(1); if (!branch[0]) return 'assignment_not_found' as const; } const target = input.assignmentType === 'employee' ? eq(devicePairingRequests.employeeId, input.assignmentId) : eq(devicePairingRequests.branchId, input.assignmentId); const at = now(); await tx.update(devicePairingRequests).set({ status: 'cancelled', cancelledAt: at, registrationChallenge: null, webauthnUserId: null }).where(and(target, eq(devicePairingRequests.status, 'pending'))); const result = await tx.insert(devicePairingRequests).values({ assignmentType: input.assignmentType, employeeId: input.assignmentType === 'employee' ? input.assignmentId : null, branchId: input.assignmentType === 'branch' ? input.assignmentId : null, tokenHash: input.tokenHash, status: 'pending', createdAt: at }); return { id: Number(result[0].insertId) }; }); },
  async getPendingPairing(tokenHash) { const pairing = (await database.select().from(devicePairingRequests).where(and(eq(devicePairingRequests.tokenHash, tokenHash), eq(devicePairingRequests.status, 'pending'))).limit(1))[0]; if (!pairing) return null; const assignmentId = pairing.assignmentType === 'employee' ? pairing.employeeId! : pairing.branchId!; const existing = await database.select({ credentialId: devices.credentialId }).from(devices).where(and(assignmentFilter(pairing.assignmentType, assignmentId), eq(devices.status, 'active'))); return { assignmentType: pairing.assignmentType, assignmentId, challenge: pairing.registrationChallenge, webauthnUserId: pairing.webauthnUserId, excludeCredentialIds: existing.map((item) => item.credentialId) }; },
  async saveRegistrationChallenge(input) { const result = await database.update(devicePairingRequests).set({ registrationChallenge: input.challenge, webauthnUserId: input.webauthnUserId }).where(and(eq(devicePairingRequests.tokenHash, input.tokenHash), eq(devicePairingRequests.status, 'pending'))); return result[0].affectedRows === 1; },
  async activatePairing(input) {
    try {
      return await database.transaction(async (tx) => {
        const candidate = (await tx.select().from(devicePairingRequests).where(eq(devicePairingRequests.tokenHash, input.tokenHash)).limit(1))[0];
        if (!candidate) return 'invalid' as const;
        if (candidate.assignmentType === 'employee') {
          const employee = await tx.select({ id: employees.id }).from(employees).where(and(eq(employees.id, candidate.employeeId!), isNull(employees.deletedAt))).for('update').limit(1);
          if (!employee[0]) return 'invalid' as const;
        } else {
          const branch = await tx.select({ id: branches.id }).from(branches).where(eq(branches.id, candidate.branchId!)).for('update').limit(1);
          if (!branch[0]) return 'invalid' as const;
        }
        const pairing = (await tx.select().from(devicePairingRequests).where(eq(devicePairingRequests.id, candidate.id)).for('update').limit(1))[0];
        if (!pairing || pairing.status !== 'pending' || pairing.registrationChallenge !== input.expectedChallenge || pairing.assignmentType !== input.assignmentType || (pairing.assignmentType === 'employee' ? pairing.employeeId : pairing.branchId) !== input.assignmentId) return 'invalid' as const;
        const markerOwner = (await tx.select().from(devices).where(eq(devices.installationMarkerHash, input.installationMarkerHash)).for('update').limit(1))[0];
        if (markerOwner) {
          const sameAssignment = markerOwner.assignmentType === input.assignmentType && (markerOwner.assignmentType === 'employee' ? markerOwner.employeeId : markerOwner.branchId) === input.assignmentId;
          if (!sameAssignment) return 'conflict' as const;
          await tx.update(devices).set({ installationMarkerHash: null }).where(eq(devices.id, markerOwner.id));
        }
        const at = now(); const target = assignmentFilter(pairing.assignmentType, input.assignmentId);
        const old = await tx.select({ id: devices.id }).from(devices).where(and(target, eq(devices.status, 'active'))).for('update');
        if (old.length) {
          await tx.update(devices).set({ status: 'revoked', revokedAt: at }).where(and(target, eq(devices.status, 'active')));
          await tx.insert(deviceHistory).values(old.map(({ id }) => ({ deviceId: id, event: 'revoked' as const, createdAt: at })));
        }
        const result = await tx.insert(devices).values({ assignmentType: pairing.assignmentType, employeeId: pairing.employeeId, branchId: pairing.branchId, credentialId: input.credentialId, credentialIdHash: input.credentialIdHash, credentialPublicKey: input.credentialPublicKey, counter: input.counter, transports: input.transports, credentialDeviceType: input.credentialDeviceType, credentialBackedUp: input.credentialBackedUp, installationMarkerHash: input.installationMarkerHash, browser: input.browser, platform: input.platform, status: 'active', pairedAt: at });
        const id = Number(result[0].insertId);
        await tx.insert(deviceHistory).values({ deviceId: id, event: 'paired', createdAt: at });
        await tx.update(devicePairingRequests).set({ status: 'used', consumedAt: at, registrationChallenge: null }).where(eq(devicePairingRequests.id, pairing.id));
        return publicDevice((await tx.select().from(devices).where(eq(devices.id, id)).limit(1))[0]!);
      });
    } catch (error) { if (duplicate(error)) return 'conflict'; throw error; }
  },
  async findActiveCredential(input) { const row = (await database.select().from(devices).where(and(assignmentFilter(input.assignmentType, input.assignmentId), eq(devices.installationMarkerHash, input.installationMarkerHash))).limit(1))[0]; if (!row) return 'invalid'; if (row.status === 'revoked') return 'revoked'; return { deviceId: row.id, credentialId: row.credentialId, credentialPublicKey: row.credentialPublicKey, counter: row.counter, transports: row.transports }; },
  async createAuthenticationChallenge(input) { return database.transaction(async (tx) => { const device = await tx.select({ status: devices.status }).from(devices).where(eq(devices.id, input.deviceId)).for('update').limit(1); if (device[0]?.status !== 'active') return false; await tx.delete(deviceAuthenticationChallenges).where(eq(deviceAuthenticationChallenges.deviceId, input.deviceId)); await tx.insert(deviceAuthenticationChallenges).values(input); return true; }); },
  async consumeAuthenticationChallenge(input) { return database.transaction(async (tx) => { const challenge = (await tx.select().from(deviceAuthenticationChallenges).where(and(eq(deviceAuthenticationChallenges.id, input.challengeId), isNull(deviceAuthenticationChallenges.consumedAt), gt(deviceAuthenticationChallenges.expiresAt, input.now))).for('update').limit(1))[0]; if (!challenge) return 'invalid' as const; const row = (await tx.select().from(devices).where(eq(devices.id, challenge.deviceId)).for('update').limit(1))[0]; if (!row) return 'invalid' as const; if (row.status === 'revoked') return 'revoked' as const; const matchesAssignment = row.assignmentType === input.assignmentType && (row.assignmentType === 'employee' ? row.employeeId : row.branchId) === input.assignmentId; if (!matchesAssignment || row.credentialIdHash !== input.credentialIdHash || row.installationMarkerHash !== input.installationMarkerHash) return 'invalid' as const; const consumed = await tx.update(deviceAuthenticationChallenges).set({ consumedAt: input.now }).where(and(eq(deviceAuthenticationChallenges.id, input.challengeId), isNull(deviceAuthenticationChallenges.consumedAt))); if (consumed[0].affectedRows !== 1) return 'invalid' as const; return { deviceId: row.id, credentialId: row.credentialId, credentialPublicKey: row.credentialPublicKey, counter: row.counter, transports: row.transports, challenge: challenge.challenge }; }); },
  async recordSuccessfulVerification(deviceId, expectedCounter, newCounter) { return database.transaction(async (tx) => { const row = (await tx.select().from(devices).where(eq(devices.id, deviceId)).for('update').limit(1))[0]; if (!row || row.counter !== expectedCounter) return 'invalid' as const; if (row.status === 'revoked') return 'revoked' as const; const at = now(); await tx.update(devices).set({ counter: newCounter, lastUsedAt: at }).where(and(eq(devices.id, deviceId), eq(devices.counter, expectedCounter))); await tx.insert(deviceHistory).values({ deviceId, event: 'verified', createdAt: at }); return publicDevice({ ...row, counter: newCounter, lastUsedAt: at }); }); },
  async cancelPairing(id) { const result = await database.update(devicePairingRequests).set({ status: 'cancelled', cancelledAt: now(), registrationChallenge: null }).where(and(eq(devicePairingRequests.id, id), eq(devicePairingRequests.status, 'pending'))); return result[0].affectedRows === 1; },
  async revoke(id) { return database.transaction(async (tx) => { const at = now(); const result = await tx.update(devices).set({ status: 'revoked', revokedAt: at }).where(and(eq(devices.id, id), eq(devices.status, 'active'))); if (result[0].affectedRows !== 1) return false; await tx.insert(deviceHistory).values({ deviceId: id, event: 'revoked', createdAt: at }); return true; }); },
  async list(query) { const filters = []; if (query.status) filters.push(eq(devices.status, query.status)); if (query.assignmentType) filters.push(eq(devices.assignmentType, query.assignmentType)); if (query.assignmentId) filters.push(query.assignmentType === 'branch' ? eq(devices.branchId, query.assignmentId) : eq(devices.employeeId, query.assignmentId)); const where = filters.length ? and(...filters) : undefined; const rows = await database.select().from(devices).where(where).orderBy(asc(devices.id)).limit(query.pageSize).offset((query.page - 1) * query.pageSize); const total = (await database.select({ value: count() }).from(devices).where(where))[0]?.value ?? 0; return { items: rows.map(publicDevice), total }; },
  async findById(id) { const row = (await database.select().from(devices).where(eq(devices.id, id)).limit(1))[0]; return row ? publicDevice(row) : null; },
  async history(id) { return database.select({ event: deviceHistory.event, createdAt: deviceHistory.createdAt }).from(deviceHistory).where(eq(deviceHistory.deviceId, id)).orderBy(asc(deviceHistory.id)); },
});

export const createDeviceLifecycle = (database: Database, now: () => Date = () => new Date()) => ({
  async revokeEmployee(employeeId: number, context?: unknown) { const tx = (context ?? database) as Database; const at = now(); await tx.select({ id: employees.id }).from(employees).where(eq(employees.id, employeeId)).for('update').limit(1); const active = await tx.select({ id: devices.id }).from(devices).where(and(eq(devices.employeeId, employeeId), eq(devices.status, 'active'))); await tx.update(devices).set({ status: 'revoked', revokedAt: at }).where(and(eq(devices.employeeId, employeeId), eq(devices.status, 'active'))); if (active.length) await tx.insert(deviceHistory).values(active.map(({ id }) => ({ deviceId: id, event: 'revoked' as const, createdAt: at }))); await tx.update(devicePairingRequests).set({ status: 'cancelled', cancelledAt: at, registrationChallenge: null }).where(and(eq(devicePairingRequests.employeeId, employeeId), eq(devicePairingRequests.status, 'pending'))); },
});
