import type { createDatabase } from '@capella/database';
import { branches, deviceHistory, devicePairingRequests, devices, employees } from '@capella/database/schema';
import { and, asc, count, eq, isNull } from 'drizzle-orm';
import type { DeviceRepository, PublicDevice } from './devices-service.js';
type Database = ReturnType<typeof createDatabase>;
const publicDevice = (row: typeof devices.$inferSelect): PublicDevice => ({ id: row.id, assignmentType: row.assignmentType, assignmentId: row.assignmentType === 'employee' ? row.employeeId! : row.branchId!, status: row.status, browser: row.browser, platform: row.platform, pairedAt: row.pairedAt, lastUsedAt: row.lastUsedAt, revokedAt: row.revokedAt });
const duplicate = (error: unknown) => typeof error === 'object' && error !== null && (Reflect.get(error, 'code') === 'ER_DUP_ENTRY' || Reflect.get(Reflect.get(error, 'cause') ?? {}, 'code') === 'ER_DUP_ENTRY');
export const createDrizzleDeviceRepository = (database: Database, now: () => Date = () => new Date()): DeviceRepository => ({
  async assignmentExists(input) { if (input.assignmentType === 'branch') return Boolean((await database.select({ id: branches.id }).from(branches).where(eq(branches.id, input.assignmentId)).limit(1))[0]); return Boolean((await database.select({ id: employees.id }).from(employees).where(and(eq(employees.id, input.assignmentId), isNull(employees.deletedAt))).limit(1))[0]); },
  async createPairing(input) { return database.transaction(async (tx) => { if (input.assignmentType === 'employee') { const employee = await tx.select({ id: employees.id }).from(employees).where(and(eq(employees.id, input.assignmentId), isNull(employees.deletedAt))).for('update').limit(1); if (!employee[0]) return 'assignment_not_found' as const; } else await tx.select({ id: branches.id }).from(branches).where(eq(branches.id, input.assignmentId)).for('update').limit(1); const target = input.assignmentType === 'employee' ? eq(devicePairingRequests.employeeId, input.assignmentId) : eq(devicePairingRequests.branchId, input.assignmentId); const at = now(); await tx.update(devicePairingRequests).set({ status: 'cancelled', cancelledAt: at }).where(and(target, eq(devicePairingRequests.status, 'pending'))); const result = await tx.insert(devicePairingRequests).values({ assignmentType: input.assignmentType, employeeId: input.assignmentType === 'employee' ? input.assignmentId : null, branchId: input.assignmentType === 'branch' ? input.assignmentId : null, tokenHash: input.tokenHash, status: 'pending', createdAt: at }); return { id: Number(result[0].insertId) }; }); },
  async completePairing(input) { try { return await database.transaction(async (tx) => { const candidate = (await tx.select().from(devicePairingRequests).where(eq(devicePairingRequests.tokenHash, input.tokenHash)).limit(1))[0]; if (!candidate) return 'invalid' as const; if (candidate.assignmentType === 'employee') { const employee = await tx.select({ id: employees.id }).from(employees).where(and(eq(employees.id, candidate.employeeId!), isNull(employees.deletedAt))).for('update').limit(1); if (!employee[0]) return 'invalid' as const; } else await tx.select({ id: branches.id }).from(branches).where(eq(branches.id, candidate.branchId!)).for('update').limit(1); const pairing = (await tx.select().from(devicePairingRequests).where(eq(devicePairingRequests.id, candidate.id)).for('update').limit(1))[0]; if (!pairing || pairing.status !== 'pending') return 'invalid' as const; const at = now(); const target = pairing.assignmentType === 'employee' ? eq(devices.employeeId, pairing.employeeId!) : eq(devices.branchId, pairing.branchId!); const old = await tx.select({ id: devices.id }).from(devices).where(and(target, eq(devices.status, 'active'))).for('update'); if (old.length) { await tx.update(devices).set({ status: 'revoked', revokedAt: at }).where(and(target, eq(devices.status, 'active'))); await tx.insert(deviceHistory).values(old.map((item) => ({ deviceId: item.id, event: 'revoked' as const, createdAt: at }))); } const result = await tx.insert(devices).values({ assignmentType: pairing.assignmentType, employeeId: pairing.employeeId, branchId: pairing.branchId, credentialIdHash: input.credentialIdHash, publicKey: input.publicKey, installationMarkerHash: input.installationMarkerHash, browser: input.browser, platform: input.platform, status: 'active', pairedAt: at }); const id = Number(result[0].insertId); await tx.insert(deviceHistory).values({ deviceId: id, event: 'paired', createdAt: at }); await tx.update(devicePairingRequests).set({ status: 'used', consumedAt: at }).where(and(eq(devicePairingRequests.id, pairing.id), eq(devicePairingRequests.status, 'pending'))); return publicDevice((await tx.select().from(devices).where(eq(devices.id, id)).limit(1))[0]!); }); } catch (error) { if (duplicate(error)) return 'conflict'; throw error; } },
  async cancelPairing(id) { const result = await database.update(devicePairingRequests).set({ status: 'cancelled', cancelledAt: now() }).where(and(eq(devicePairingRequests.id, id), eq(devicePairingRequests.status, 'pending'))); return result[0].affectedRows === 1; },
  async revoke(id) { return database.transaction(async (tx) => { const at = now(); const result = await tx.update(devices).set({ status: 'revoked', revokedAt: at }).where(and(eq(devices.id, id), eq(devices.status, 'active'))); if (result[0].affectedRows !== 1) return false; await tx.insert(deviceHistory).values({ deviceId: id, event: 'revoked', createdAt: at }); return true; }); },
  async verify(input) { return database.transaction(async (tx) => { const assignment = input.assignmentType === 'employee' ? eq(devices.employeeId, input.assignmentId) : eq(devices.branchId, input.assignmentId); const row = (await tx.select().from(devices).where(and(assignment, eq(devices.credentialIdHash, input.credentialIdHash), eq(devices.installationMarkerHash, input.installationMarkerHash))).limit(1))[0]; if (!row) return 'invalid'; if (row.status === 'revoked') return 'revoked'; const at = now(); await tx.update(devices).set({ lastUsedAt: at }).where(eq(devices.id, row.id)); await tx.insert(deviceHistory).values({ deviceId: row.id, event: 'verified', createdAt: at }); return publicDevice({ ...row, lastUsedAt: at }); }); },
  async list(query) { const filters = []; if (query.status) filters.push(eq(devices.status, query.status)); if (query.assignmentType) filters.push(eq(devices.assignmentType, query.assignmentType)); if (query.assignmentId) filters.push(query.assignmentType === 'branch' ? eq(devices.branchId, query.assignmentId) : eq(devices.employeeId, query.assignmentId)); const where = filters.length ? and(...filters) : undefined; const rows = await database.select().from(devices).where(where).orderBy(asc(devices.id)).limit(query.pageSize).offset((query.page - 1) * query.pageSize); const total = (await database.select({ value: count() }).from(devices).where(where))[0]?.value ?? 0; return { items: rows.map(publicDevice), total }; },
  async findById(id) { const row = (await database.select().from(devices).where(eq(devices.id, id)).limit(1))[0]; return row ? publicDevice(row) : null; },
  async history(id) { return database.select({ event: deviceHistory.event, createdAt: deviceHistory.createdAt }).from(deviceHistory).where(eq(deviceHistory.deviceId, id)).orderBy(asc(deviceHistory.id)); },
});

export const createDeviceLifecycle = (database: Database, now: () => Date = () => new Date()) => ({
  async revokeEmployee(employeeId: number, context?: unknown) {
    const tx = (context ?? database) as Database;
    const at = now();
    await tx.select({ id: employees.id }).from(employees).where(eq(employees.id, employeeId)).for('update').limit(1);
    const active = await tx.select({ id: devices.id }).from(devices).where(and(eq(devices.employeeId, employeeId), eq(devices.status, 'active')));
    await tx.update(devices).set({ status: 'revoked', revokedAt: at }).where(and(eq(devices.employeeId, employeeId), eq(devices.status, 'active')));
    if (active.length) await tx.insert(deviceHistory).values(active.map(({ id }) => ({ deviceId: id, event: 'revoked' as const, createdAt: at })));
    await tx.update(devicePairingRequests).set({ status: 'cancelled', cancelledAt: at }).where(and(eq(devicePairingRequests.employeeId, employeeId), eq(devicePairingRequests.status, 'pending')));
  },
});
