'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Badge, Button, Card, CardContent, EmptyState, Input, Label } from '@capella/ui';
import { DataTable, TD, TH, THead, TR } from '@/components/data/data-table';
import { FieldError } from '@/components/feedback/notice';
import { LoadingState } from '@/components/feedback/loading-state';
import { Select } from '@/components/form/select';
import { PageHeader, SectionHeading } from '@/components/layout/page-header';
import { useSession } from '@/features/auth';
import { listCatalogBranches } from '@/features/catalog';
import { listAllProducts } from '@/features/products';
import { ApiError } from '@/lib/api/client';
import { completeServiceExecutions, configureConsumable, correctServiceExecution, listConsumableBalances, listConsumableServices, transferConsumableStock } from '../api/consumables-api';
type Usage = { productId: number | ''; quantity: string };
const errorText = (error: unknown) => error instanceof ApiError ? error.message : 'تعذر تنفيذ العملية.';
export function ConsumablesView() {
  const queryClient = useQueryClient(); const session = useSession(); const isAdmin = session.data?.actor.type === 'admin';
  const [branchId, setBranchId] = useState<number | undefined>(() => { if (typeof window === 'undefined') return undefined; const value = Number(new URLSearchParams(window.location.search).get('branchId')); return value > 0 ? value : undefined; }); const ready = session.isSuccess && (!isAdmin || branchId !== undefined);
  const [status, setStatus] = useState<'pending' | 'completed' | 'overdue'>('pending'); const [selected, setSelected] = useState<number[]>([]);
  const [usages, setUsages] = useState<Usage[]>([{ productId: '', quantity: '' }]);
  const [configProductId, setConfigProductId] = useState<number | ''>(() => { if (typeof window === 'undefined') return ''; const value = Number(new URLSearchParams(window.location.search).get('productId')); return value > 0 ? value : ''; }); const [unit, setUnit] = useState<'ml' | 'gm'>('ml'); const [packageSize, setPackageSize] = useState('');
  const [transferProductId, setTransferProductId] = useState<number | ''>(''); const [direction, setDirection] = useState<'reserve' | 'return'>('reserve'); const [packages, setPackages] = useState('1');
  const [correctingId, setCorrectingId] = useState<number>(); const [correctionReason, setCorrectionReason] = useState('');
  const params = branchId === undefined ? {} : { branchId }; const branches = useQuery({ queryKey: ['consumables-branches'], queryFn: () => listCatalogBranches(), enabled: isAdmin });
  const products = useQuery({ queryKey: ['consumables-products', branchId], queryFn: () => listAllProducts(params), enabled: ready && isAdmin });
  const balances = useQuery({ queryKey: ['consumables-balances', branchId], queryFn: () => listConsumableBalances({ ...params, pageSize: 100 }), enabled: ready });
  const services = useQuery({ queryKey: ['consumables-services', branchId, status], queryFn: () => listConsumableServices({ ...params, status, pageSize: 100 }), enabled: ready });
  const refresh = async () => {
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['consumables-balances'] }),
      queryClient.invalidateQueries({ queryKey: ['consumables-services'] }),
    ]);
  };
  const validUsages = usages.filter((entry): entry is { productId: number; quantity: string } => typeof entry.productId === 'number' && Number(entry.quantity) > 0);
  const complete = useMutation({ mutationFn: () => completeServiceExecutions({ ...params, serviceQueueEntryIds: selected, usages: validUsages }), onSuccess: async () => { setSelected([]); await refresh(); } });
  const configure = useMutation({ mutationFn: () => configureConsumable(Number(configProductId), { ...params, unit, packageSize }), onSuccess: refresh });
  const transfer = useMutation({ mutationFn: () => transferConsumableStock(Number(transferProductId), { ...params, direction, packages: Number(packages) }), onSuccess: refresh });
  const correct = useMutation({ mutationFn: () => correctServiceExecution(correctingId!, { ...params, reason: correctionReason, usages: validUsages }), onSuccess: async () => { setCorrectingId(undefined); setCorrectionReason(''); await refresh(); } });
  const mutations = [complete, configure, transfer, correct]; const pending = mutations.some((item) => item.isPending); const failed = mutations.find((item) => item.isError);
  return <section className="space-y-6"><PageHeader title="المستهلكات والخدمات" description="إدارة رصيد ml/gm وإنهاء تقرير مستقل لكل خدمة مباعة." />
    {isAdmin ? <Card><CardContent className="space-y-4 p-4"><div><Label htmlFor="consumables-branch">الفرع</Label><Select id="consumables-branch" value={branchId ?? ''} onChange={(event) => { setBranchId(event.target.value ? Number(event.target.value) : undefined); setSelected([]); }}><option value="">اختر الفرع</option>{branches.data?.items.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></div>{ready ? <div className="grid gap-4 lg:grid-cols-2"><div className="space-y-3"><SectionHeading title="إعداد منتج كمستهلك" /><Select aria-label="منتج إعداد المستهلك" value={configProductId} onChange={(event) => setConfigProductId(event.target.value ? Number(event.target.value) : '')}><option value="">اختر المنتج</option>{products.data?.items.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</Select><div className="flex gap-2"><Select aria-label="وحدة المستهلك" value={unit} onChange={(event) => setUnit(event.target.value as 'ml' | 'gm')}><option value="ml">ml</option><option value="gm">gm</option></Select><Input aria-label="حجم العبوة" type="number" min="0.001" step="0.001" value={packageSize} onChange={(event) => setPackageSize(event.target.value)} /></div><Button disabled={!configProductId || !Number(packageSize) || pending} onClick={() => configure.mutate()}>حفظ إعداد المستهلك</Button></div><div className="space-y-3"><SectionHeading title="تحويل عبوات كاملة" /><Select aria-label="منتج التحويل" value={transferProductId} onChange={(event) => setTransferProductId(event.target.value ? Number(event.target.value) : '')}><option value="">اختر المستهلك</option>{balances.data?.items.map((item) => <option key={item.productId} value={item.productId}>{item.productName}</option>)}</Select><div className="flex gap-2"><Select aria-label="اتجاه التحويل" value={direction} onChange={(event) => setDirection(event.target.value as 'reserve' | 'return')}><option value="reserve">حجز من مخزون البيع</option><option value="return">إرجاع لمخزون البيع</option></Select><Input aria-label="عدد العبوات" type="number" min="1" step="1" value={packages} onChange={(event) => setPackages(event.target.value)} /></div><Button disabled={!transferProductId || !Number(packages) || pending} onClick={() => transfer.mutate()}>تنفيذ التحويل</Button></div></div> : null}</CardContent></Card> : null}
    {!ready ? <EmptyState title="اختر فرعاً للمتابعة" /> : <><Card><CardContent className="p-4"><SectionHeading title="أرصدة المستهلكات" />{balances.isPending ? <LoadingState label="جارٍ التحميل…" /> : <DataTable><THead><TH>المنتج</TH><TH numeric>مخزون البيع</TH><TH numeric>رصيد المستهلك</TH><TH numeric>حجم العبوة</TH></THead><tbody>{balances.data?.items.map((item) => <TR key={item.productId}><TD>{item.productName}</TD><TD numeric>{item.sellableQuantity}</TD><TD numeric>{item.consumableQuantity} {item.unit}</TD><TD numeric>{item.packageSize} {item.unit}</TD></TR>)}</tbody></DataTable>}</CardContent></Card>
      <Card><CardContent className="space-y-4 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><SectionHeading title="تقارير الخدمات" /><Select aria-label="حالة الخدمة" value={status} onChange={(event) => { setStatus(event.target.value as typeof status); setSelected([]); }}><option value="pending">غير منتهية</option><option value="completed">منتهية</option><option value="overdue">متأخرة</option></Select></div>{services.isPending ? <LoadingState label="جارٍ تحميل الخدمات…" /> : <DataTable><THead>{status !== 'completed' ? <TH>اختيار</TH> : null}<TH>الخدمة</TH><TH>الدور</TH><TH>الفاتورة</TH><TH>العميل</TH><TH>الموظف</TH>{status === 'completed' ? <TH>الإجراء</TH> : null}</THead><tbody>{services.data?.items.map((item) => <TR key={item.id}>{status !== 'completed' ? <TD><input aria-label={`اختيار الخدمة ${item.queueNumber}`} type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((ids) => ids.includes(item.id) ? ids.filter((id) => id !== item.id) : [...ids, item.id])} /></TD> : null}<TD>{item.serviceName}</TD><TD><Badge>{item.queueNumber}</Badge></TD><TD>{item.invoiceNumber}</TD><TD>{item.clientName ?? item.clientPhone ?? '—'}</TD><TD>{item.employeeName ?? '—'}</TD>{status === 'completed' ? <TD><Button size="sm" variant="ghost" onClick={() => setCorrectingId(item.id)}>تصحيح</Button></TD> : null}</TR>)}</tbody></DataTable>}
        {(status !== 'completed' || correctingId) ? <div className="space-y-3 border-t border-line pt-4"><SectionHeading title={correctingId ? 'تصحيح الاستهلاك' : `إنهاء ${selected.length} خدمة`} />{usages.map((usage, index) => <div className="flex flex-wrap gap-2" key={index}><Select aria-label={`المستهلك ${index + 1}`} value={usage.productId} onChange={(event) => setUsages((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, productId: event.target.value ? Number(event.target.value) : '' } : row))}><option value="">بدون مستهلك / اختر منتجاً</option>{balances.data?.items.map((item) => <option key={item.productId} value={item.productId}>{item.productName} ({item.unit})</option>)}</Select><Input aria-label={index === 0 ? 'كمية المستهلك' : `كمية المستهلك ${index + 1}`} type="number" min="0.001" step="0.001" value={usage.quantity} onChange={(event) => setUsages((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, quantity: event.target.value } : row))}/>{usages.length > 1 ? <Button variant="ghost" onClick={() => setUsages((rows) => rows.filter((_, rowIndex) => rowIndex !== index))}>حذف</Button> : null}</div>)}<Button variant="secondary" onClick={() => setUsages((rows) => [...rows, { productId: '', quantity: '' }])}>إضافة مستهلك</Button>{correctingId ? <><Input aria-label="سبب التصحيح" value={correctionReason} onChange={(event) => setCorrectionReason(event.target.value)} /><Button disabled={!correctionReason.trim() || pending} onClick={() => correct.mutate()}>حفظ التصحيح</Button></> : <Button disabled={!selected.length || pending} onClick={() => complete.mutate()}>إنهاء الخدمات المحددة</Button>}</div> : null}{failed ? <FieldError>{errorText(failed.error)}</FieldError> : null}</CardContent></Card></>}
  </section>;
}
